---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurantmgt-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurantmgt
  template:
    metadata:
      labels:
        app: restaurantmgt
    spec:
      containers:
        - name: restaurantmgt
          image: ratheeshku/restaurantmgt
          ports:
            - containerPort: 8080
          env:
            - name: DB_Config
              value: host=postgres user=postgres password=Rev@thy25 dbname=restaurant
                port=5432 sslmode=disable
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: ""

---

apiVersion: v1
kind: Service
metadata:
  name: restaurantmgt-service
spec:
  type: NodePort
  selector:
    app: restaurantmgt
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000  
      
# apiVersion: v1
# kind: Service
# metadata:
#   name: restaurantmgt-service
# spec:
#   selector:
#     app: restaurantmgt
#   ports:
#     - protocol: TCP
#       port: 8080
#       targetPort: 8080
#       nodePort: 30080
#   type: NodePort
